# Site settings
title: Ares
description: 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: TeamAres
user_description: Ares is a Rover being built by NSIT undergrads for Mars Exploration
user_title: Engineering a Martian Rover
email: teamaresnsit@gmail.com
twitter_username: TeamARES
github_username:  TeamARES
gplus_username:  AresNSIT

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
